version: "{build}"
clone_folder: "c:\\WORK"

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http"
  matrix:
    - GHCVER: "9.0.1"
    - GHCVER: "8.10.4"
    - GHCVER: "8.8.4"
    - GHCVER: "8.6.5"
    - GHCVER: "8.4.4"
    - GHCVER: "8.2.2"
    - GHCVER: "8.0.2"
    - GHCVER: "7.10.3.2"
    # - GHCVER: "7.8.4.1"  fails

#  allow_failures:
#    - GHCVER: "7.8.4.1"

cache:
 - "C:\\SR"

install:
 - "choco install -y cabal"
 - "choco install -y ghc --version %GHCVER%"
 - "refreshenv"
 - "set PATH=C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% update -vverbose+nowrap"

build: off

test_script:
 - IF EXIST configure.ac bash -c "autoreconf -i"
 - "cabal %CABOPTS% new-build -j1 -vnormal+nowrap --dry all"
 - ps: Push-AppveyorArtifact dist-newstyle\cache\plan.json
 - "cabal %CABOPTS% new-build -j1 -vnormal+nowrap all"
 - "cabal %CABOPTS% new-test  -j1 -vnormal+nowrap all"
